### PR TITLE
Autodeploy docs to gh-pages

### PR DESCRIPTION
**Pull request by monkeez**
I had to merge the GitHub workflows into one yml file to get the `docs` job to depend on the `maya` job. The benefit is now the `deploy` job also depends on the `maya` job so it'll only push releases to PyPI that have passed the tests.

### CODE REVIEW

**Comment by monkeez** [comment]
Resolves #53

**Comment by mottosso** [comment]
Nice!

> I had to merge the GitHub workflows into one yml file to get the docs job to depend on the maya job.

Why was that? I didn't think the docs needed the results of the build anyway?

> The benefit is now the deploy job also depends on the maya job so it'll only push releases to PyPI that have passed the tests.

I actually specifically made it so we could deploy without going through yet another build. Since deployment only happens from the master branch, and nothing is merged with master unless it builds, it just adds friction. And the few times when you actually do want to deploy with a failing build, now we can't. :(

So ideally, deploy would remain separate. Is that possible you think?

**Comment by mottosso** [comment]
Ok, I see now. Docs are built with mayapy.. That makes sense.. In that case, this looks solid. Let's try it!

**Comment by monkeez** [comment]
Deploy could still be separate if you like, you'd just have to add the `deploy.yml` back and remove the `deploy` job from `main.yml`. I'd imagine that would all still work OK.

**Comment by mottosso** [comment]
That's true, deploy and docs could remain separate. Oh well, let's give this a try and see what problems if any come out of it. Thanks @monkeez!

**Pull request merged**
